# Generated by Django 5.2.5 on 2025-08-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='worker',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
