# Generated by Django 5.2.5 on 2025-08-18 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_worker_profile_image_url_worker_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
