# Generated by Django 5.2.4 on 2025-08-22 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_authenticateduser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
