# Generated by Django 5.2.5 on 2025-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worker_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='sentiment_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], db_index=True, default='neutral', max_length=10),
        ),
    ]
