# Generated by Django 5.2.4 on 2025-08-29 08:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
