# Generated by Django 5.2.5 on 2025-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
