# Generated by Django 5.2.5 on 2025-09-02 14:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_worker_average_rating_worker_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkerData',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.userreview')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.TextField()),
                ('worker_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('worker_experience', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('num_bookings', models.IntegerField(default=0)),
                ('total_rating', models.FloatField(default=0.0)),
                ('rating', models.FloatField()),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('user_review', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
            options={
                'db_table': 'user_worker_data',
            },
        ),
    ]
