# Generated by Django 5.2.5 on 2025-09-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userworkerdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_type',
        ),
        migrations.AlterField(
            model_name='userworkerdata',
            name='charge',
            field=models.IntegerField(default=0),
        ),
    ]
