# Generated by Django 5.2.5 on 2025-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_name_service_service_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkerdata',
            old_name='service_type',
            new_name='service_description',
        ),
    ]
