# Generated by Django 5.2.5 on 2025-09-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_service_type_userworkerdata_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkerdata',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userworkerdata',
            name='sentiment_score',
        ),
        migrations.RemoveField(
            model_name='userworkerdata',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='userworkerdata',
            name='user_review',
        ),
    ]
