# Generated by Django 5.2.5 on 2025-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_userworkerdata_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerservice',
            name='charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
