# Generated by Django 5.2.5 on 2025-09-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workerservice_charge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='verifierreview',
            name='application',
        ),
        migrations.RemoveField(
            model_name='verifierreview',
            name='verifier',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='sentiment',
        ),
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='VerifierReview',
        ),
    ]
