# Generated by Django 5.2.5 on 2025-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_recommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authenticateduser',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
