# Generated by Django 5.2.5 on 2025-09-05 09:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_authenticateduser_address_authenticateduser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='authenticateduser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=10, region=None),
        ),
    ]
