# Generated by Django 5.2.5 on 2025-09-06 01:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_authenticateduser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=20, region=None),
        ),
    ]
