# Generated by Django 5.2.5 on 2025-09-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_authenticateduser_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
    ]
