# Generated by Django 5.2.5 on 2025-09-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_razorpaypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
