# Generated by Django 5.2.5 on 2025-09-11 11:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_authenticateduser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=30, region=None),
        ),
    ]
