# Generated by Django 5.2.5 on 2025-09-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_authenticateduser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.booking')),
            ],
        ),
    ]
