# Generated by Django 5.2.5 on 2025-09-24 01:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_booking_details_bookingphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingphoto',
            options={'verbose_name': 'Booking Photo', 'verbose_name_plural': 'Booking Photos'},
        ),
        migrations.AlterModelOptions(
            name='razorpaypayment',
            options={'verbose_name': 'Razorpay Payment', 'verbose_name_plural': 'Razorpay Payments'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterModelOptions(
            name='workerservice',
            options={'verbose_name': 'Worker Service', 'verbose_name_plural': 'Worker Services'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='job_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('coins', 'Coins'), ('cod', 'Cash on Delivery'), ('online', 'Online')], default='coins', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.worker'),
        ),
        migrations.AlterField(
            model_name='razorpaypayment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payment', to='core.booking'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workerapplication'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profiles/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerservice',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.worker'),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='bookingphoto',
            table='booking_photos',
        ),
        migrations.AlterModelTable(
            name='razorpaypayment',
            table='razorpay_payments',
        ),
        migrations.AlterModelTable(
            name='worker',
            table='workers',
        ),
        migrations.AlterModelTable(
            name='workerservice',
            table='worker_services',
        ),
    ]
