# Generated by Django 5.2.5 on 2025-09-24 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_booking_options_alter_bookingphoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.booking')),
            ],
            options={
                'db_table': 'tariffs',
            },
        ),
    ]
