# Generated by Django 5.2.5 on 2025-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_booking_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
