# Generated by Django 5.2.5 on 2025-09-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.worker'),
        ),
    ]
