# Generated by Django 5.2.5 on 2025-10-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_booking_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='core.worker')),
            ],
            options={
                'db_table': 'worker_earnings',
            },
        ),
    ]
