# Generated by Django 5.2.5 on 2025-10-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_workerearning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='userreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
