# Generated by Django 5.2.5 on 2025-10-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_userreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userworkerdata',
            unique_together={('user', 'worker', 'service')},
        ),
        migrations.AddField(
            model_name='userworkerdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='userworkerdata',
            name='review',
        ),
    ]
