# Generated by Django 5.2.5 on 2025-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_userworkerdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkerdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
