# Generated by Django 5.2.5 on 2025-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_userworkerdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkerdata',
            name='worker_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkerdata',
            name='worker_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
